#ifndef CHAOS_SETTINGS_H
#define CHAOS_SETTINGS_H

#define SOFTWARE_VERSION "1.0"

#define CHAOS_PRODUCT_TYPE "OPER"
#define CHAOS_PRODUCT_CODE "CH7"
#define EXPORT_VERSION_STRING "0101"

#define CDF_GZIP_COMPRESSION_LEVEL 6

#define CDF_BLOCKING_FACTOR 43200

#endif //CHAOS_SETTINGS_H
